"""bugfix: correct active to is_active

Revision ID: cb98a72750ab
Revises: 7685fd00e696
Create Date: 2021-12-03 12:16:09.979253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb98a72750ab'
down_revision = '7685fd00e696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False))
    op.drop_column('cards', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('cards', 'is_active')
    # ### end Alembic commands ###
